### ISSUE TITLE
Increase Accuracy

### ISSUE THREAD

**Issue by TabishKhan-007** [auejin/winklick#1]
Sir 
when we install application then the pupil detection are very slow and also the cursor movement .How to increase it like  your video

**Comment by auejin** [comment]
Thank you for your interest in this system! I wrote this code when I was a sophomore in high school with little knowledge in programming. Since the model I used for this system is heuristic with several parameters tuned for myself, I believe the external validity is pretty limited. I think numerous methods for pupil detection have been presented with much better performance for the past five years, so I would recommend you to try those!
